package aoc.day07

import kotlin.test.Test
import kotlin.test.assertEquals

val DUMMY_INPUT = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............""".trimIndent()

class DayTest {

    @Test
    fun solveTest() {
        val world = World.parseText(DUMMY_INPUT)
        assertEquals(21, solvePart1(world))
        assertEquals(40_uL, solvePart2(world))
    }

}